# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4513d760d5bb9016f08ce42e591d29684ad743c51d79a919674173d204c36507f70a5ee58326df5bde26472295d9a29e6e35ae969f4a8f67b7f3b8c3df18277e

test:
  secret_key_base: e1a09123e53e1cf3d4b25ad0bb74d31aeb35b6f328d0bca1e70aa89a479bfb70f1ba4fa1b8ed5947e13e47b88699076e01450822b09eb487534b3ee4d0ad5ab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
