# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d90f64f0037df3de96ee0b64b430ef58c8de4d9a0bb5884dffcc0eb84555787d5c74b0d9537b91b518fd8277033609b8d12920999e41282b4b0bd23a28b8d2b

test:
  secret_key_base: 9f477ade68aceb8c4f035e13848fc925283058c6614eb84d893bc0d72a17a52b898ef45e93e481d3b37e20e34118fbe0bc66256d4f9f1f1527e33896a798f696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
